name: retro_infinity_scroll
description: A Flutter plugin to implement infinity scroll and inflact paginated data into a ListView.
version: 0.0.3
homepage: https://github.com/SmarttersStudio/retro_infinity_scroller

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
